config/routes.rb
HeartSelf::Application.routes.draw do
  #authenticated :user do
    #root :to => 'home#index'
  #end
  root :to => "home#index"
  match "/custom" => "home#custom", :as => "custom"
  match "/taobao" => "home#taobao", :as => "taobao"
  match "/display" => "home#display", :as => "display"
  match "/quality" => "home#quality", :as => "quality"
  match "/myproductions" => "home#myproductions", :as => "myproductions"
  devise_for :users
  resources :users
  resources :productions
  resources :user_productions, :only => [:edit, :update, :new, :create]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
  def custom
    @production = Production.new
  end
  def taobao
    #@user = current_user
  end
  def display
    @user_production_grid = initialize_grid(UserProduction, :order => 'user_productions.is_sold', :per_page => 30)
  end
  def quality
    #@user = current_user
  end
  def myproductions
    @productions = current_user.productions
    render 'productions/index'
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def active?(controller_name_action_name)
    "#{self.controller_name}##{self.action_name}"==controller_name_action_name ? "active" : nil
  end
end

app/views/home/custom.html.haml
%div#custom-photos
  .pull-left#line
    = link_to "开始定制旅程的记忆", new_production_path(:p_type => "facet"), :class => "btn btn-blue btn-large"
  .pull-right#dot  
    = link_to "开始定制熟悉的点", new_production_path(:p_type => "radial"), :class => "btn btn-large btn-pink"
.clearfix  
%h1 “心私”现在可以选择两种以上的定制
-#%p= @user.email

app/views/home/display.html.haml
%h2 交易管理
= grid(@user_production_grid, show_filters: :when_filtered) do |g|
  - g.column :name => 'ID', :attribute => 'id', :filter => false do |task|
    - task.id


  - g.column :name => '用户' do |task|
    - link_to task.user.name, task.user


  - g.column :name => '产品' do |task|
    - link_to "#{task.production.p_color} #{task.production.p_material} #{task.production.p_pattern}", task.production


  - g.column :name => '订于', :attribute => 'order_at' do |task|
    - l(task.order_at, format: :long)


  - g.column :name => '已出售', :attribute => 'is_sold', :filter => false do |task|
    - task.is_sold ? "Yes" : "No"


  - g.column :name => '售于', :attribute => 'sold_at' do |task|
    - l(task.sold_at, format: :long)


  - g.column :name => '原价' do |task|
    - task.production.price


  - g.column :name => '交易价' do |task|
    - task.bargain_price


  - g.column   do |task|
    - link_to '编辑', edit_user_production_path(task.id), :class => ""

app/views/home/index.html.haml
-#%h3 Home
-#- @users.each do |user|
  -#%p
    -#User: #{link_to user.name, user}
%div#photos
  =image_tag("http://meshu.io/static/images/photos/meshu04.jpg", class:"pull-left")
  =image_tag("http://meshu.io/static/images/photos/meshu03.jpg", class:"pull-left")
  %div.right.pull-left
    %div#intro-text
      %div.title 心私
      %p 把最私密的地点传递最美的首饰给你
    %div.custom
      %button.btn.btn-large.btn-blue 用新浪微博开始定制
      %br
      %button.btn.btn-large.btn-pink 直接开始开始定制
    %div.also
      %p 你还可以
      %button.btn.btn-large.btn-gray 用街旁网连接
      或
      %br
      %br
      %button.btn.btn-large.btn-gray 看看别人的作品

%div.clearfix
%div#story.section
  %h1 每个“心私”都在讲述一个故事
  =image_tag("http://meshu.io/static/images/samples/macro0.jpg", class:"center")



%div.clearfix
%div#custom.section
  %h1 “心私”是怎么定制的？
  %div.image-text.pull-left
    =image_tag("http://meshu.io/static/images/diagrams/diagrams_01.png", class:"center")
    %p 进入地图选择城市，点击您曾经去过或喜欢的地方。

  %div.image-text.pull-left
    =image_tag("http://meshu.io/static/images/diagrams/diagrams_02.png", class:"center")
    %p 心私会定做出属于您唯一的吊坠、耳环、耳坠或挂件。
    
  %div.image-text.pull-left
    =image_tag("http://meshu.io/static/images/diagrams/diagrams_03.png", class:"center")
    %p 我们为您提供精心打造的包装和送货上门的物流服务。



%div.clearfix
%div#unique.section
  %h1 每个“心私”都是独一无二的私心和爱
  =image_tag("http://meshu.io/static/images/diagrams/postcard_shoot_web.jpg", class:"center")
    
%div.clearfix
  %div#about-custom.section
    %p
      已定制
      %span.number 5516
      份心私
    %h1 您准备好定制了吗？
    %div.middle
      %button.btn.btn-large.btn-gray 看看大家的作品
      %button.btn.btn-large.btn-pink 开始您的定制
    %p 
      你也可以连接
      %button.btn.btn-blue 新浪微博
      或
      %button.btn.btn-blue 街旁网
      使用踩过的地点

app/views/home/quality.html.haml
%p quality

app/views/home/taobao.html.haml
%p taobao dian