config/routes.rb
HeartSelf::Application.routes.draw do
  #authenticated :user do
    #root :to => 'home#index'
  #end
  root :to => "home#index"
  match "/custom" => "home#custom", :as => "custom"
  match "/taobao" => "home#taobao", :as => "taobao"
  match "/display" => "home#display", :as => "display"
  match "/quality" => "home#quality", :as => "quality"
  match "/myproductions" => "home#myproductions", :as => "myproductions"
  devise_for :users
  resources :users
  resources :productions
  resources :user_productions, :only => [:edit, :update, :new, :create]
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
#logo= link_to image_tag("http://meshu.io/static/images/logo.png"), root_path, :class => 'brand'
%ul.nav.nav-pills
  %li{:class => active?("home#index")}
    = link_to '首页', root_path
  %li{:class => active?("home#custom")}
    = link_to '定制', custom_path
  %li{:class => active?("home#taobao")}
    = link_to '淘宝店', taobao_path
  %li{:class => active?("productions#index")}
    = link_to '展示', productions_path
  %li{:class => active?("home#quality")}
    = link_to '品与质', quality_path

%ul.nav.pull-right  
  - if user_signed_in?
    %li.dropdown#user-manage
      %a.dropdown-toggle{:"data-toggle" => "dropdown", :href => "#user-manage"}
        = current_user.name
        %b.caret
      %ul.dropdown-menu
        %li
          = link_to '用户编辑', edit_user_registration_path
        %li
          = link_to '我的心私', myproductions_path
        - if current_user.has_role? :admin  
          %li
            = link_to '用户管理', users_path
          %li
            = link_to '交易管理', display_path
        %li
          = link_to '注销', destroy_user_session_path, :method=>'delete' 
  - else
    %li
      = link_to '登录', new_user_session_path
    %li
      = link_to '注册', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Heart Self"
      %meta{:content => content_for?(:description) ? yield(:description) : "Heart Self", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
    %script{:type => "text/javascript", :src  => "http://api.map.baidu.com/api?v=1.5&ak=87fbca56e51d40372f2af58bd89e22a5"}    
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
      / ! end of .container
    / ! end of #main
    
    %footer.container
      .inner
        .pull-left
          copyright &copy; 2011-2012 xinsi.me, All Rights Reversed.
        .pull-right
          %span 关于我们
          %span 加入我们
          %span 合作联系

    = debug(params) if Rails.env.development?